### ISSUE TITLE
Failed to set up - HA 2023.6.2

### ISSUE THREAD

**Issue by TheCruelSloth** [h4de5/home-assistant-toshiba_ac#129]
After updating to HA 2023.6.2 and OS version 10.2 I'm getting te following error.
Do you have any idea what causes this and how to solve it?

```
Logger: homeassistant.config_entries
Source: custom_components/toshiba_ac/__init__.py:34
Integration: Toshiba AC ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 10:46:02 (1 occurrences)
Last logged: 10:46:02

Error setting up entry ********* for toshiba_ac
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.pipeline.pipeline_exceptions.OperationTimeout: OperationTimeout('Transport timeout on connection operation')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device_manager.py", line 64, in connect
    self.amqp_api = ToshibaAcAmqpApi(self.sas_token)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/utils/amqp_api.py", line 35, in __init__
    self.device.on_method_request_received = self.method_request_received
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/abstract_clients.py", line 479, in on_method_request_received
    self._generic_receive_handler_setter(
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 161, in _generic_receive_handler_setter
    fut.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 113, in _enable_feature
    await handle_result(callback)
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 59, in handle_result
    raise exceptions.OperationTimeout(
azure.iot.device.exceptions.OperationTimeout: OperationTimeout('Could not complete operation before timeout') caused by OperationTimeout('Transport timeout on connection operation')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/__init__.py", line 34, in async_setup_entry
    await device_manager.connect()
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device_manager.py", line 72, in connect
    await self.shutdown()
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device_manager.py", line 93, in shutdown
    results = await asyncio.gather(*tasks, return_exceptions=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

**Comment by whentotrade** [comment]
same here. no idea where to start analyzing. any ideas?

**Comment by h4de5** [comment]
does the official toshiba app works for you? because I do not get any devices there either.

**Comment by beandi** [comment]
Same problem here with an older version of HA, seems like the cloud service is broken.

**Comment by TheCruelSloth** [comment]
> does the official toshiba app works for you? because I do not get any devices there either.<

Right now it's also down for me. But it was working this morning.

**Comment by Sebazzz** [comment]
The command to downgrade is: `ha core downgrade --version 2023.6.1`

But that doesn't help as apparently the Toshiba app is also not working, it was a few minutes ago though.

**Comment by beandi** [comment]
App, Cloud service and integration is working again under HA 2023.6.1

**Comment by Sebazzz** [comment]
Also under 2023.6.2.

**Comment by h4de5** [comment]
i think it was a service outage on toshibas side.
