### ISSUE TITLE
some entities are unaviable after upgrade to 2023.10.3

### ISSUE THREAD

**Issue by SebaGaillard74** [h4de5/home-assistant-toshiba_ac#147]
Hello everyone!

I have some issues since I've updated to the latest core version of HA.

Some AC are marked as unavailable

Here are the logs:

2023-10-18 01:54:49.236 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform toshiba_ac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 338, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
                             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/climate.py", line 121, in preset_mode
    if self._device.ac_self_cleaning == ToshibaAcSelfCleaning.ON:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device/__init__.py", line 363, in ac_self_cleaning
    return self.fcu_state.ac_self_cleaning
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device/fcu_state.py", line 461, in ac_self_cleaning
    return ToshibaAcFcuState.AcSelfCleaning.from_raw(self._ac_self_cleaning)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device/fcu_state.py", line 246, in from_raw
    return {
           ^
KeyError: 0

Can you help me?

Thanks

**Comment by h4de5** [comment]
please reopen if this is still an issue
