### ISSUE TITLE
HA failing to setup integration after updating Adapter version to 2.4.00

### ISSUE THREAD

**Issue by taher51** [h4de5/home-assistant-toshiba_ac#159]
Hi All,

I am experiencing a new issue where the Toshiba AC integration is now failing to load. The only new thing I have done recently is update the adapter version in the internal units to version 2.4.00.

My setup:
Toshiba Haori 
R32 RAS5M....... external unit.

Below is the error I am seeing. Any help would be much appreciated.

Logger: custom_components.toshiba_ac.config_flow
Source: custom_components/toshiba_ac/config_flow.py:77
Integration: Toshiba AC ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 18:35:19 (1 occurrences)
Last logged: 18:35:19

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.pipeline.pipeline_exceptions.OperationTimeout: OperationTimeout('Transport timeout on connection operation')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/toshiba_ac/config_flow.py", line 77, in async_step_user
    data = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/config_flow.py", line 41, in validate_input
    sas_token = await device_manager.connect()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/device_manager.py", line 64, in connect
    self.amqp_api = ToshibaAcAmqpApi(self.sas_token)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toshiba_ac/utils/amqp_api.py", line 35, in __init__
    self.device.on_method_request_received = self.method_request_received
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/abstract_clients.py", line 479, in on_method_request_received
    self._generic_receive_handler_setter(
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 161, in _generic_receive_handler_setter
    fut.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 113, in _enable_feature
    await handle_result(callback)
  File "/usr/local/lib/python3.11/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 59, in handle_result
    raise exceptions.OperationTimeout(
azure.iot.device.exceptions.OperationTimeout: OperationTimeout('Could not complete operation before timeout') caused by OperationTimeout('Transport timeout on connection operation')

**Comment by beandi** [comment]
Not much helpful, but after upgrading to 2.4.00 everything still works fine. I'm yet still on HA 2023.10.1

**Comment by taher51** [comment]
This has been resolved with the latest update of this integration.
