### ISSUE TITLE
Module 'janus' not found

### ISSUE THREAD

**Issue by janipewter** [h4de5/home-assistant-toshiba_ac#180]
This integration worked well for me for a while, but in the last few weeks it is broken. I see this in the home assistant logs:
```
2024-05-05 16:45:49.797 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'toshiba_ac': Unable to import component: No module named 'janus'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1001, in async_get_component
    self._component_future.result()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 981, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1041, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 144, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/toshiba_ac/__init__.py", line 4, in <module>
    from toshiba_ac.device_manager import ToshibaAcDeviceManager
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/device_manager.py", line 19, in <module>
    from toshiba_ac.device import ToshibaAcDevice
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 37, in <module>
    from toshiba_ac.utils.amqp_api import ToshibaAcAmqpApi
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/utils/amqp_api.py", line 21, in <module>
    from azure.iot.device.aio import IoTHubDeviceClient  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/azure/iot/device/aio/__init__.py", line 8, in <module>
    from azure.iot.device.iothub.aio import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/__init__.py", line 7, in <module>
    from .async_clients import IoTHubDeviceClient, IoTHubModuleClient
  File "/config/.local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 24, in <module>
    from .async_inbox import AsyncClientInbox
  File "/config/.local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_inbox.py", line 8, in <module>
    import janus
ModuleNotFoundError: No module named 'janus'
```

I'm using HA docker from lscr.io on Unraid

**Comment by h4de5** [comment]
fixed this locally like this: 
https://github.com/KaSroka/Toshiba-AC-control/issues/47

not sure why this is not a problem for the most users. can add it to the version soon.
