### ISSUE TITLE
Devices not found

### ISSUE THREAD

**Issue by koen-venly** [h4de5/home-assistant-toshiba_ac#183]
`` 
Entity None (<class 'custom_components.toshiba_ac.climate.ToshibaClimate'>) implements HVACMode(s): off, auto, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/h4de5/home-assistant-toshiba_ac/issues 
 ``

Error:
`
Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toshiba_ac/climate.py", line 50, in async_setup_entry
    devices = await device_manager.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device_manager.py", line 185, in get_devices
    await asyncio.gather(*connects)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 112, in connect
    await self.load_additional_device_info()
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 120, in load_additional_device_info
    additional_info = await self.http_api.get_device_additional_info(self.ac_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 173, in get_device_additional_info
    res = await self.request_api(self.AC_STATE_PATH, get=get)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 98, in request_api
    json = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mobileapi.toshibahomeaccontrols.com/api/AC/GetCurrentACState?ACId=dd172d8e-b363-4c99-a510-189e952d81fb')
``
`
 [140201734130496] Preset mode is not valid. Valid preset modes are: Power 50, Power 75, Power 100 
`

**Comment by jtosic** [comment]
Happened to me after update to Home Assistant v2024.7.4 - I had to reinstall integration in order to get it to work again. Credentials got messed up or something as accesing that URL will display error in XML:

Authorization has been denied for this request.

**Comment by albaintor** [comment]
Probably the same issue as the one that I resolved in https://github.com/h4de5/home-assistant-toshiba_ac/issues/207
