### ISSUE TITLE
Integration stopped working and reinstall gives "Unknown error occurred" 

### ISSUE THREAD

**Issue by ozmafin** [h4de5/home-assistant-toshiba_ac#206]
Hi everyone,
before anything I would like to thank all the contributors for this HA integration! Thank you so much <3

**Home Assistant Core** 2024.9.3
**Frontend** 20240909.1
**HACS version** 2.0.1
**HACS Toshiba AC plugin version** 2024.9.0

**AC model**: RAS-B13N4KVRG-E
**AC Adapter version** 2.4.00

The integration stopped working. Tried to reconfigure Toshiba AC HACS plugin and got "Unexpected error". Username is LLNNNNN password is LlllllllllNNN (L = Uppercase letter, l = lowercase letter, N = number). Changed password for user, didn't help. Tried to log in with different user (have 3 of them) - didn't help. Tried #151 and it's good. I can log in to the service from iOS app with all 3 users. 

I also tried to compare if this is something to do with #72 but I couldn't figure out if I needed to do something or if this is the same. 

Logs:
2024-10-01 10:15:13.906 ERROR (MainThread) [custom_components.toshiba_ac.config_flow] Toshiba connection OK
2024-10-01 10:15:13.906 ERROR (MainThread) [custom_components.toshiba_ac.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/__init__.py", line 90, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 100, in request_api
    async with method(url, **method_args) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1301, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/toshiba_ac/config_flow.py", line 82, in async_step_user
    data = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/config_flow.py", line 43, in validate_input
    sas_token = await device_manager.connect()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device_manager.py", line 63, in connect
    await self.http_api.connect()
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 120, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/__init__.py", line 63, in wrapper
    return await asyncio.wait_for(func(*args, **kwargs), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by Sabreu** [comment]
I have same issue since updating to HA 2024.10. Nothing seems to help.

Toshiba app working fine.

**Comment by timongrob** [comment]
Same here. Integration stopped working, toshiba app working fine

**Comment by timongrob** [comment]
I went back to version 2024.6.1 and all is working fine again in Home Assistant

**Comment by h4de5** [comment]
checkout latest release #214

**Comment by Sabreu** [comment]
@h4de5 
I still encounter this error with new release
```
2024-12-08 10:38:43.280 ERROR (MainThread) [custom_components.toshiba_ac.config_flow] Toshiba connection OK
2024-12-08 10:38:43.280 ERROR (MainThread) [custom_components.toshiba_ac.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/__init__.py", line 90, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 103, in request_api
    async with method(url, **method_args) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1360, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 538, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/toshiba_ac/config_flow.py", line 82, in async_step_user
    data = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/config_flow.py", line 43, in validate_input
    sas_token = await device_manager.connect()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device_manager.py", line 63, in connect
    await self.http_api.connect()
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 126, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/__init__.py", line 63, in wrapper
    return await asyncio.wait_for(func(*args, **kwargs), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

```

**Comment by h4de5** [comment]
please understand that the integration and the API below are depending on the online services from toshiba. if their servers are not reachable - for whatever reason - there is nothing much we can do.

**Comment by Sabreu** [comment]
Toshiba app is working fine from my home network so can it be online service issue?
Also as timongrob stated earlier going back to HA 2024.6 the HA component started to work again.
I have not downgraded HA myself.

**Comment by Sabreu** [comment]
python toshiba_ac_gui.py seems to work fine also, it seemed to also fail first but after changing password it started to work.
From homeassistant the toshiba integration still fails... I don't understand where the problem could be..

**Comment by Sabreu** [comment]
And found the issue finally. nslookup mobileapi.toshibahomeaccontrols.com revealed it from the HA container.
HA could not access my pihole server and seems like the secondary dns 1.1.1.1 gave the IP once but then nslookup timeouted three times again the pihole dns ip.
I removed pihole from unraid server dns server list and only use 1.1.1.1 and 1.0.0.1 and it immediately worked
