### ISSUE TITLE
HA integration breaks under HA Core 2024.11.2

### ISSUE THREAD

**Issue by johnbrady833** [h4de5/home-assistant-toshiba_ac#211]
I upgraded HA to HA Core 2024.11.2. The Toshiba AC integration stopped working.

The logs showed a series of errors, including:

Initial connection failed, trying to get new sas_token...
Platform toshiba_ac does not generate unique IDs.

I've rolled back to HA Core 2024.11.1 and it's working again.

**Comment by dlysnes** [comment]
I experience same issues too. It helps reloading it for a few minutes, but then it fails with "Failed to perform the action <whatever> 'b' format requires -128 <= number <= 127" whenever I try to do.
I've seen some other intgrations have issues with websockets version after upgrade. Might be related?

**Comment by pjylkka** [comment]
dublicate of #208

**Comment by manuvbv** [comment]
Hi i don't know is it's the same issue, i have the same issue since last update of HA core, here my logs :

2024-11-25 13:53:31.542 ERROR (MainThread) [homeassistant.components.overkiz] Error fetching device events data: Too many requests, try again later.
2024-11-25 14:24:25.960 ERROR (MainThread) [custom_components.toshiba_ac] Unload Toshiba integration
2024-11-25 14:24:25.961 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry xxxxxx for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 233, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-11-25 14:24:25.970 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry xxxxxx for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 109, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-11-25 14:24:25.975 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry xxxxxx for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 138, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-11-25 14:24:25.985 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry xxxxxx for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 99, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by h4de5** [comment]
please check latest release.
If the error persists, please make sure it is not related to a possible restricted access to the Toshiba API before reopening the issue.
