### ISSUE TITLE
Add integration fails with "config flow could not be loaded"

### ISSUE THREAD

**Issue by istvanstahl** [h4de5/home-assistant-toshiba_ac#34]
Version: Home Assistant 2021.9.7

2022-01-13 10:01:29 ERROR (MainThread) [homeassistant.components.upnp] Unexpected error fetching Wireless Router TL-WR1043ND data: invalid literal for int() with base 10: '4 Days, 19:59:19'
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/upnp/__init__.py", line 209, in _async_update_data
    update_values = await asyncio.gather(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/upnp/device.py", line 165, in async_get_status
    values = await asyncio.gather(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/profiles/igd.py", line 406, in async_get_status_info
    result = await action.async_call()
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 547, in async_call
    response_args = self.parse_response(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 612, in parse_response
    return self._parse_response_args(service_type, xml)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 648, in _parse_response_args
    arg.upnp_value = arg_xml.text or ""
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 430, in upnp_value
    self._value = self.coerce_python(upnp_value)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 434, in coerce_python
    return self.related_state_variable.coerce_python(upnp_value)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/async_upnp_client/client.py", line 813, in coerce_python
    return coercer(upnp_value)
ValueError: invalid literal for int() with base 10: '4 Days, 19:59:19'
2022-01-13 10:02:44 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of toshiba-ac==0.1.12
2022-01-13 10:03:03 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package toshiba-ac==0.1.12: ERROR: Cannot install toshiba-ac==0.1.12 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
2022-01-13 10:03:03 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)

**Comment by h4de5** [comment]
Unable to install package toshiba-ac==0.1.12: ERROR: Cannot install toshiba-ac==0.1.12 because these package versions have conflicting dependencies.

it seems Home-assistant changed some pip-package requirements.

As this is seems to be a problem with the underlying api package, can you please open up a ticket there:

https://pypi.org/project/toshiba-ac/
https://github.com/KaSroka/Toshiba-AC-control

**Comment by h4de5** [comment]
Added a new release - let me know if the problem is fixed.
