### ISSUE TITLE
Device unavailable after update to 2022.2.1

### ISSUE THREAD

**Issue by haseat** [h4de5/home-assistant-toshiba_ac#41]
After updating to 2022.2.1, I get following error messages:

```
Logger: homeassistant.components.climate
Source: custom_components/toshiba_ac/climate.py:182
Integration: Climate (documentation, issues)
First occurred: 04:39:41 (4 occurrences)
Last logged: 05:17:40

Error adding entities for domain climate with platform toshiba_ac
Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 210, in state
    return self.hvac_mode
  File "/config/custom_components/toshiba_ac/climate.py", line 234, in hvac_mode
    if not self.is_on:
  File "/config/custom_components/toshiba_ac/climate.py", line 182, in is_on
    return self._device.ac_status == ToshibaAcFcuState.AcStatus.ON
AttributeError: type object 'AcStatus' has no attribute 'ON'

```
Downgrading to 2021.9.5 and everything works again.

**Comment by h4de5** [comment]
should be fixed with  997ab17bd03cdaf10bdf4d5a9eb6f91822524f9e in 2022.2.2
