### ISSUE TITLE
Device unavaliable

### ISSUE THREAD

**Issue by Kahera** [h4de5/home-assistant-toshiba_ac#48]
Today I started getting the following error (potentially related to updating to 2022.4.5): 

```
Logger: homeassistant.components.climate
Source: custom_components/toshiba_ac/climate.py:455
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 21:26:43 (2 occurrences)
Last logged: 21:26:43

Error adding entities for domain climate with platform toshiba_ac
Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 799, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/toshiba_ac/climate.py", line 455, in extra_state_attributes
    "merit_b_feature": self._device.ac_merit_b.name,
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 327, in ac_merit_b
    return self.fcu_state.ac_merit_b
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 420, in ac_merit_b
    return ToshibaAcFcuState.AcMeritB.from_raw(self._ac_merit_b)
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 176, in from_raw
    return {
KeyError: 1
```

I have not tried downgrading, the problem persists in 2022.4.6.

**Comment by Kahera** [comment]
The device has returned. Assuming it was a Toshiba API issue or something.
