### ISSUE TITLE
Unexpected exception importing platform custom_components.toshiba_ac.climate

### ISSUE THREAD

**Issue by benvanmierloo** [h4de5/home-assistant-toshiba_ac#57]
Hi,

I've just installed the toshiba_ac integration. When setting up the integration, I can succesfully sign in, but after adding the AC units (5 in total), only the first one shows up with only 1 entity (the outside temperature). 

Afterwards i get following message in the logs:

```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/toshiba_ac/climate.py:212
Integration: Toshiba AC (documentation, issues)
First occurred: 3:45:15 PM (1 occurrences)
Last logged: 3:45:15 PM

Unexpected exception importing platform custom_components.toshiba_ac.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/toshiba_ac/climate.py", line 59, in <module>
    class ToshibaClimate(ToshibaAcEntity, ClimateEntity):
  File "/config/custom_components/toshiba_ac/climate.py", line 212, in ToshibaClimate
    def hvac_mode(self) -> HVACMode | str | None:
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'
```

**Comment by h4de5** [comment]
if possible, please downgrade to previous version. It may take some time until I'll be able to fix it.

**Comment by benvanmierloo** [comment]
tested your change, it works now!

you are awesome! 👍
