### ISSUE TITLE
Add-on toshiba don't work

### ISSUE THREAD

**Issue by gmarongiu71** [h4de5/home-assistant-toshiba_ac#68]
Today the add-on don't work.
Toshiba shorai edge with FW ver 4.0
Thanks

**Comment by tetienne** [comment]
Hi,

Just say doesn't work is not enough to receive some help.

Please give some context and all the logs related to this component.

**Comment by gmarongiu71** [comment]
Hi, The day before yesterday there was a FW update to version 4.0. Iniltre an application update was released that if not done, it was written, that the toshiba application for Android would no longer work.
Today, having already tried to remove and re-enter the account, I find both the 4 indoor units (such as Climate) and the 4 temperature and eternal sensors associated with the individual splits.
The temperature sensors are functional, while the climate sensors are not.

LOG:

2022-07-01 13:14:52 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform toshiba_ac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/toshiba_ac/climate.py", line 325, in extra_state_attributes
    "merit_b_feature": self._device.ac_merit_b.name,
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 327, in ac_merit_b
    return self.fcu_state.ac_merit_b
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 420, in ac_merit_b
    return ToshibaAcFcuState.AcMeritB.from_raw(self._ac_merit_b)
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 176, in from_raw
    return {
KeyError: 1
2022-07-01 13:14:53 ERROR (MainThread) [homeassistant.components.climate] Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/toshiba_ac/climate.py", line 325, in extra_state_attributes
    "merit_b_feature": self._device.ac_merit_b.name,
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 327, in ac_merit_b
    return self.fcu_state.ac_merit_b
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 420, in ac_merit_b
    return ToshibaAcFcuState.AcMeritB.from_raw(self._ac_merit_b)
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/fcu_state.py", line 176, in from_raw
    return {
KeyError: 1

**Comment by h4de5** [comment]
does the new android app (v3.3.0) work with the old AC firmware (prios to v4)? now i am afraid to update..

@KaSroka are you up for a restart?

if i get time, i'll have a look at the new app - if they only changed the endpoint it may not be much ..
https://apkpure.com/toshiba-home-ac-control/com.toshibatctc.SmartAC/versions

**Comment by gmarongiu71** [comment]
> does the new android app (v3.3.0) work with the old AC firmware (prios to v4)? now i am afraid to update..
> 
> @KaSroka are you up for a restart?
> 
> if i get time, i'll have a look at the new app - if they only changed the endpoint it may not be much ..

I'm afraid that from 14/07 they will change something on the server side and therefore the update will become mandatory

**Comment by chrisandsally** [comment]
I got the message on my iPhone but on version 3.3.0 already and eveything still works in HA. I clicked on ignore for now.  Does this still mean it may break HA after 14th July?

**Comment by gmarongiu71** [comment]
> I got the message on my iPhone but on version 3.3.0 already and eveything still works in HA. I clicked on ignore for now. Does this still mean it may break HA after 14th July?

 Ut have you got update the shorai fw at 4.0 version?

**Comment by h4de5** [comment]
> does the new android app (v3.3.0) work with the old AC firmware (prios to v4)? now i am afraid to update..
> 
> @KaSroka are you up for a restart?
> 
> if i get time, i'll have a look at the new app - if they only changed the endpoint it may not be much .. https://apkpure.com/toshiba-home-ac-control/com.toshibatctc.SmartAC/versions

seems I already hit a limit - the new version has its .dll files packed and obfuscated in an assemblies/assemblies.blob file, which I cannot open at the moment. so I can't even get to the dll files to reverse them.

so - for now I would just skip the firmware update as long as possible - and hope that they dont shutdown the old servers in the middle of the summer ..

**Comment by gmarongiu71** [comment]
> > does the new android app (v3.3.0) work with the old AC firmware (prios to v4)? now i am afraid to update..
> > @KaSroka are you up for a restart?
> > if i get time, i'll have a look at the new app - if they only changed the endpoint it may not be much .. https://apkpure.com/toshiba-home-ac-control/com.toshibatctc.SmartAC/versions
> 
> seems I already hit a limit - the new version has its .dll files packed and obfuscated in an assemblies/assemblies.blob file, which I cannot open at the moment. so I can't even get to the dll files to reverse them.
> 
> so - for now I would just skip the firmware update as long as possible - and hope that they dont shutdown the old servers in the middle of the summer ..

If it helps, it works with Alexa platform.

**Comment by dimvas243** [comment]
hi i have 2 a/c from toshiba that yesterday ask me for update i diden't see that with the new update FW 2.0 from 1.9 for me they will not work the one is shorai edge and the other is haori. The strange thing for mw is the that the haori is working fine from the HA after the update, the shorai edge is not. i don't know if it helps at all but i founded very strange

**Comment by chrisandsally** [comment]
I went for it, upgraded firmware to version 4.00 (Adapter) iPhone app on 3.3.0 and all still works within HA. I don’t know if it is a haori unit or not, can’t see any labels. If this helps.

**Comment by dimvas243** [comment]
now they are working both fine for me

**Comment by gmarongiu71** [comment]
Shorai edge with one external Unit and 4 internal.
Today work also for me, but first I have made this procedure:
-Reload the add-on (yet not work and in the climate ha is present but N/A) 
- restar ha (yet not work and again as above) 
- on and off single internal device (yet don't work, but now see the selec temperature) 
- wating about 30 minutes and work.

If I reload the add-on i must repeat all procedure.

**Comment by recklezz** [comment]
For my Seiya everything works, except the Airco Outdoor Temperature.

**Comment by dominicusmento** [comment]
seems that it worked for me too.. after updating my WIFI adapter RB-N106S-G on fw2.0, shorai edge, the problems started.
Simply turning the AC on and leaving it on for some time helped and now it works again from HA..

**Comment by recklezz** [comment]
Same, it started working again for me to with my Seiya.

**Comment by gmarongiu71** [comment]
Today my clima don't work.
Same problem indicate in head at this post.

**Comment by jirieibel** [comment]
Still not working, anyone has solution?


Unexpected exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

Traceback (most recent call last):
  File "/config/custom_components/toshiba_ac/config_flow.py", line 77, in async_step_user
    data = await validate_input(self.hass, user_input)
  File "/config/custom_components/toshiba_ac/config_flow.py", line 41, in validate_input
    sas_token = await device_manager.connect()
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/device_manager.py", line 59, in connect
    await self.http_api.connect()
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/http_api.py", line 117, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/http_api.py", line 98, in request_api
    async with method(url, **method_args) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:default [Name does not resolve]
