### ISSUE TITLE
Stop Working one AC

### ISSUE THREAD

**Issue by Mik-3DXT** [h4de5/home-assistant-toshiba_ac#71]
Hi,
After update home assistat to the last release i have lost one AC of two device.
I view the outdoor temperature but not the climate entity.

I had already upgrade the fw to 4.0 version and all worked fine, until upgrade home assistant 
This is the log:

Logger: homeassistant.components.climate
Source: custom_components/toshiba_ac/climate.py:325
Integration: Termostato (documentation, issues)
First occurred: 16:04:41 (2 occurrences)
Last logged: 16:04:41

Error adding entities for domain climate with platform toshiba_ac
Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/toshiba_ac/climate.py", line 325, in extra_state_attributes
    "merit_b_feature": self._device.ac_merit_b.name,
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/device.py", line 327, in ac_merit_b
    return self.fcu_state.ac_merit_b
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/fcu_state.py", line 420, in ac_merit_b
    return ToshibaAcFcuState.AcMeritB.from_raw(self._ac_merit_b)
  File "/usr/local/lib/python3.10/site-packages/toshiba_ac/fcu_state.py", line 176, in from_raw
    return {
KeyError: 1

Thanks

**Comment by Berni86** [comment]
Hi, 
I have the same error.
I had HA 2022.7.3 and fw 1.9 and everything was working fine. After update fw to 2.0 climate entity stopped working, outdoor temperature works fine.

Thanks

**Comment by sozzledspam** [comment]
I can join the club :)
I have a multi split unit with 3 devices. I can still operate 1 device via HA. The outside temp and the first added air conditioning still works. The other 2 are nog available.

**Comment by Berni86** [comment]
It works now :),
Since I updated the firmware I had never turned it on from the AC remote control always from toshiba app. When turning it on from remote control and restarting HA, the climate entity has been loaded correctly. Try it!!
thanks all.

**Comment by sozzledspam** [comment]
genius. that's the solution. kinda strange actually but it is working. Kudo's

**Comment by h4de5** [comment]
please keep in mind they announced the end date of the old api working as the 14. of july. so let us see tomorrow :)

**Comment by sozzledspam** [comment]
And it stopt working again.

**Comment by h4de5** [comment]
> > they announced the end date of the old api working as the 14
> 
> hello @h4de5
> 
> where did you find that info ?

when i open up the old app it says the update is required after the 14th of july.

**Comment by jirieibel** [comment]
HI,
 same here. I try to reinstall integration and now during setup getting Unexpected error and Invalid flow specified.
